import type { Category, Product, Promotion } from './types';

export const fallbackCategories: Category[] = [
  { id: 1, name: 'Fruits et legumes', slug: 'fruits-legumes', description: 'Selection quotidienne de produits frais.', imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&q=80', active: true, displayOrder: 1 },
  { id: 2, name: 'Boucherie et volailles', slug: 'boucherie-volailles', description: 'Viandes et volailles pour une cuisine genereuse.', imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=900&q=80', active: true, displayOrder: 2 },
  { id: 3, name: 'Produits laitiers', slug: 'produits-laitiers', description: 'Laits, yaourts, fromages et essentiels du frais.', imageUrl: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=900&q=80', active: true, displayOrder: 3 },
  { id: 4, name: 'Epicerie salee', slug: 'epicerie-salee', description: 'Pates, riz, huiles et bases de placard.', imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80', active: true, displayOrder: 4 },
  { id: 5, name: 'Boissons', slug: 'boissons', description: 'Eaux, jus, sodas et boissons familiales.', imageUrl: 'https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?auto=format&fit=crop&w=900&q=80', active: true, displayOrder: 5 },
  { id: 6, name: 'Maison et entretien', slug: 'maison-entretien', description: 'Produits utiles pour une maison propre.', imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80', active: true, displayOrder: 6 },
];

export const fallbackProducts: Product[] = [
  { id: 1, categoryId: 1, categoryName: 'Fruits et legumes', name: 'Tomates rondes selection', slug: 'tomates-rondes-selection', description: 'Tomates rouges calibrees, parfaites pour salades, sauces et plats mijotes.', brand: 'Primeur Ziouziou', sku: 'FM-FL-001', unitLabel: 'kg', price: 3.95, oldPrice: 4.6, imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 2, categoryId: 1, categoryName: 'Fruits et legumes', name: 'Bananes premium', slug: 'bananes-premium', description: 'Bananes douces et regulieres, selectionnees pour leur maturite.', brand: 'Tropicana Fresh', sku: 'FM-FL-002', unitLabel: 'kg', price: 5.49, imageUrl: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 3, categoryId: 1, categoryName: 'Fruits et legumes', name: 'Pommes rouges croquantes', slug: 'pommes-rouges-croquantes', description: 'Pommes rouges juteuses a chair ferme pour encas et desserts.', brand: 'Verger du Nord', sku: 'FM-FL-003', unitLabel: 'kg', price: 6.9, oldPrice: 7.9, imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=700&q=80', active: true, featured: false, availableQuantity: 48 },
  { id: 4, categoryId: 2, categoryName: 'Boucherie et volailles', name: 'Escalope de poulet frais', slug: 'escalope-poulet-frais', description: 'Escalopes de poulet tendres, faciles a griller ou paner.', brand: 'Beldi Selection', sku: 'FM-BV-001', unitLabel: 'kg', price: 18.9, oldPrice: 21.5, imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 5, categoryId: 2, categoryName: 'Boucherie et volailles', name: 'Viande hachee boeuf', slug: 'viande-hachee-boeuf', description: 'Boeuf hache pour kefta, sauces et preparations familiales.', brand: 'Boucherie Fraiche', sku: 'FM-BV-002', unitLabel: 'kg', price: 34.9, imageUrl: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=700&q=80', active: true, featured: false, availableQuantity: 0 },
  { id: 6, categoryId: 3, categoryName: 'Produits laitiers', name: 'Lait demi-ecreme 1L', slug: 'lait-demi-ecreme-1l', description: 'Lait UHT demi-ecreme pour le petit dejeuner et les recettes.', brand: 'Delice', sku: 'FM-PL-001', unitLabel: '1 L', price: 1.65, imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 7, categoryId: 3, categoryName: 'Produits laitiers', name: 'Yaourt nature pack familial', slug: 'yaourt-nature-pack-familial', description: 'Pack pratique de yaourts nature, texture onctueuse.', brand: 'Vitalait', sku: 'FM-PL-002', unitLabel: '8 x 110 g', price: 4.75, oldPrice: 5.2, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 8, categoryId: 3, categoryName: 'Produits laitiers', name: 'Fromage fondu portions', slug: 'fromage-fondu-portions', description: 'Portions de fromage fondu pour sandwichs et gouters.', brand: 'President', sku: 'FM-PL-003', unitLabel: '16 portions', price: 6.8, imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=700&q=80', active: true, featured: false, availableQuantity: 48 },
  { id: 9, categoryId: 4, categoryName: 'Epicerie salee', name: 'Huile d olive vierge extra', slug: 'huile-olive-vierge-extra', description: 'Huile d olive tunisienne au gout fruite pour cuisson et assaisonnement.', brand: 'Terroir Tunisien', sku: 'FM-ES-001', unitLabel: '1 L', price: 24.9, oldPrice: 28.5, imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 10, categoryId: 4, categoryName: 'Epicerie salee', name: 'Pates spaghetti', slug: 'pates-spaghetti', description: 'Spaghetti de ble dur, tenue parfaite a la cuisson.', brand: 'Randa', sku: 'FM-ES-002', unitLabel: '500 g', price: 1.89, imageUrl: 'https://images.unsplash.com/photo-1551462147-37885acc36f1?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 11, categoryId: 4, categoryName: 'Epicerie salee', name: 'Riz long grain', slug: 'riz-long-grain', description: 'Riz long grain pour plats quotidiens, accompagnements et salades.', brand: 'Le Chef', sku: 'FM-ES-003', unitLabel: '1 kg', price: 4.25, oldPrice: 4.85, imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=700&q=80', active: true, featured: false, availableQuantity: 48 },
  { id: 12, categoryId: 5, categoryName: 'Boissons', name: 'Eau minerale pack', slug: 'eau-minerale-pack', description: 'Pack familial d eau minerale pour la maison et le bureau.', brand: 'Sabrine', sku: 'FM-BO-001', unitLabel: '6 x 1.5 L', price: 3.9, imageUrl: 'https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 13, categoryId: 5, categoryName: 'Boissons', name: 'Jus orange sans pulpe', slug: 'jus-orange-sans-pulpe', description: 'Jus d orange frais et equilibre, ideal au petit dejeuner.', brand: 'Tropico', sku: 'FM-BO-002', unitLabel: '1 L', price: 3.25, oldPrice: 3.9, imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 14, categoryId: 5, categoryName: 'Boissons', name: 'Soda cola pack', slug: 'soda-cola-pack', description: 'Pack de canettes cola pour repas, receptions et moments conviviaux.', brand: 'Coca-Cola', sku: 'FM-BO-003', unitLabel: '6 x 33 cl', price: 7.9, imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=700&q=80', active: true, featured: false, availableQuantity: 0 },
  { id: 15, categoryId: 6, categoryName: 'Maison et entretien', name: 'Lessive liquide fraicheur', slug: 'lessive-liquide-fraicheur', description: 'Lessive liquide concentree pour linge propre et parfum durable.', brand: 'Omo', sku: 'FM-ME-001', unitLabel: '2 L', price: 18.5, oldPrice: 21.9, imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=700&q=80', active: true, featured: true, availableQuantity: 48 },
  { id: 16, categoryId: 6, categoryName: 'Maison et entretien', name: 'Nettoyant multi-surfaces', slug: 'nettoyant-multi-surfaces', description: 'Nettoyant quotidien pour cuisine, salle de bain et surfaces lavables.', brand: 'Mr Propre', sku: 'FM-ME-002', unitLabel: '1 L', price: 5.9, imageUrl: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=700&q=80', active: true, featured: false, availableQuantity: 48 },
];

export const fallbackPromotions: Promotion[] = [
  { id: 1, name: 'Offres fraicheur du weekend', description: 'Selection de produits frais a prix reduit.', discountType: 'PERCENTAGE', discountValue: 15, startsAt: '2026-07-01T00:00:00Z', endsAt: '2026-08-31T23:59:59Z', active: true, productIds: [1, 4, 7, 13] },
  { id: 2, name: 'Prix malins maison', description: 'Economies immediates sur les essentiels.', discountType: 'FIXED_AMOUNT', discountValue: 2, startsAt: '2026-07-01T00:00:00Z', endsAt: '2026-08-31T23:59:59Z', active: true, productIds: [9, 11, 15] },
];
